{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sightline.fullname" . }}-backend
  namespace: {{ include "sightline.namespace" . }}
  labels:
    {{- include "sightline.backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "sightline.backend.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sightline.fullname" . }}-frontend
  namespace: {{ include "sightline.namespace" . }}
  labels:
    {{- include "sightline.frontend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "sightline.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
