{{- if .Values.secrets.gcpProjectId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sightline.fullname" . }}-secrets
  namespace: {{ include "sightline.namespace" . }}
  labels:
    {{- include "sightline.labels" . | nindent 4 }}
type: Opaque
data:
  GOOGLE_CLOUD_PROJECT: {{ .Values.secrets.gcpProjectId | b64enc | quote }}
  {{- if .Values.secrets.gcpSaKey }}
  gcp-sa-key.json: {{ .Values.secrets.gcpSaKey | b64enc | quote }}
  {{- end }}
{{- end }}
