{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sightline.serviceAccountName" . }}
  namespace: {{ include "sightline.namespace" . }}
  labels:
    {{- include "sightline.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.gcpServiceAccount }}
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
